### ISSUE TITLE
The brightness of white

### ISSUE THREAD

**Issue by davids74** [TheEconomist/dark#4]
Thanks you for developing this beautiful extension. 

May I ask you where do I adjust the brightness of the white text. I like how black the black background is. But the brightness of white seems a little bit too contrasting for me. Is there a color code entry somewhere in css I could edit please?

Thank you in advance!

**Comment by eteeselink** [comment]
(note, i'm not a maintainer)

Just edit this line here https://github.com/TheEconomist/dark/blob/f97e040d78f6015261e9796dd1efb751ad3fe955/dark.css#L4
I suspect you'll also need to replace the `#f9f9f9f`s in this file https://github.com/TheEconomist/dark/blob/f97e040d78f6015261e9796dd1efb751ad3fe955/content.js#L6

try it out! those 2 files are all there is to this extension, it's positively tiny. edit away :-)  you might need to remove and then re-add the extension, not sure.

**Comment by davids74** [comment]
Ty

**Comment by contrasting** [comment]
I've dimmed it a bit
